from . import res_aisladores
from . import res_basescutout
from . import res_celdas_conexiones
from . import res_celdas_equipos
from . import res_celdas_seccionadores
from . import res_celdas
from . import res_enlaces
from . import res_fusibles
from . import res_pararrayos
from . import res_seccionadores
from . import res_seccionalizadores
from . import res_trafos_corto
from . import res_trafos_dielectrico
from . import res_trafos_equipos
from . import res_trafos_relacion
from . import res_trafos_resultados
from . import res_trafos_vacio
from . import res_trafos
from . import trafos_inspec_docus
