language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-unidecode
      - antiword  # document module
      - cups
      - libcups2-dev

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="ubar_custom,astikar_custom,galaxia_custom,rockbotic_custom,rockbotic_website_crm,pesa_custom,hispaled_custom"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="ubar_custom,astikar_custom,galaxia_custom,rockbotic_custom,rockbotic_website_crm,pesa_custom,hispaled_custom"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="hispaled_custom"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="hispaled_custom"
  # - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="ubar_custom"
  # - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="ubar_custom"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="astikar_custom"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="astikar_custom"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="galaxia_custom"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="galaxia_custom"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="rockbotic_custom"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="rockbotic_custom" 

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/avanzosc/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_wait travis_run_tests

after_success:
  - travis_after_tests_success
