# Copyright 2026 Inael
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    "name": "Ina Mp Lat Res Ensayos",
    "version": "18.0.1.0.0",
    "category": "Inael mp",
    "license": "AGPL-3",
    "author": "INAEL,jag",
    "website": "https://github.com/avanzosc/custom-addons",
    "depends": ["mrp", "ina_mc_permisos"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_aisladores.xml",
        "views/res_basescutout.xml",
        "views/res_celdas_conexiones.xml",
        "views/res_celdas_equipos.xml",
        "views/res_celdas_seccionadores.xml",
        "views/res_celdas.xml",
        "views/res_enlaces.xml",
        "views/res_fusibles.xml",
        "views/res_pararrayos.xml",
        "views/res_seccionadores.xml",
        "views/res_seccionalizadores.xml",
        "views/res_trafos_relacion.xml",
        "views/res_trafos_vacio.xml",
        "views/res_trafos_corto.xml",
        "views/res_trafos_dielectrico.xml",
        "views/res_trafos_resultados.xml",
        "views/res_trafos_equipos.xml",
        "views/res_trafos.xml",
        "wizard/wiz_celdares_duplicar.xml",
        "wizard/wiz_trafos_duplicar.xml",
        "wizard/wiz_informe_celdas.xml",
        "wizard/wiz_informe_fusibles.xml",
        "wizard/wiz_informe_secciona.xml",
        "wizard/wiz_informe_pararray.xml",
        "wizard/docu_inspec_trafos_ver.xml",
    ],
    "installable": True,
}
