# -*- coding: utf-8 -*-
# © 2015 Esther Martín - AvanzOSC
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

{
    "name": "Galaxia - Custom",
    "version": "8.0.2.1.0",
    "category": "Custom Module",
    "license": "AGPL-3",
    "author": "AvanzOSC",
    "website": "http://www.avanzosc.es",
    "contributors": [
        "Esther Martín <esthermartin@avanzosc.es>",
    ],
    "depends": [
        "analytic",
        "account_analytic_analysis",
        "account_payment_partner",
        "event",
        "sale_mrp",
        "sale_product_variants",
        "sale_stock_product_variants",
        "product_variants_types",
        "sale_order_line_attached_check",
        "sale_order_line_performance",
        "sale_service_recurrence_configurator",
        "sale_order_line_service_view",
        "website_quote_not_unlink",
        "sale_order_create_event_hour",
        "product",
        "project",
        "stock",
        "account_voucher",
        "quality_control_mrp",
        "quality_control_stock",
        "crm",
        "product_upgrade_sale_cost_price",
        "product_variant_cost_price",
        "project_work_time_control",
        "sale_order_training_plan",
        "event_track_info",
        "event_track_merge",
        "sale_order_back2draft"
    ],
    "data": [
        "data/request_link_data.xml",
        "data/decimal_precision_data.xml",
        "views/product_view.xml",
        "views/event_view.xml",
        "views/account_analytic_view.xml",
        "views/sale_order_view.xml",
        "views/account_view.xml",
        "views/crm_view.xml",
        "views/project_task_view.xml",
        "views/event_track_view.xml",
        "wizard/wiz_export_presence_information_view.xml",
        "wizard/wiz_export_csv.xml",
        "report/galaxia_layout_view.xml",
        "report/galaxia_reports.xml",
        "report/galaxia_custom_view.xml",
        "report/event_track_presence_report_view.xml",
        "security/project_task_work.xml",
    ],
    "installable": True,
    "external_dependencies": {
        'python': ["pyExcelerator"],
    },
}
