from . import res_partner
from . import stock_picking_shipping_type
from . import sale_order_line_agent
from . import sale_order_type
from . import stock_warehouse
from . import sale_order
from . import sale_order_line
from . import account_invoice
from . import res_config_settings
from . import product_pricelist
from . import product_pricelist_item
from . import product_template
from . import product_product
from . import stock_move_line
from . import stock_move
from . import stock_picking
from . import project_task
from . import account_payment_order
from . import crm_team
from . import account_move
